#!/bin/bash

lein compile
gsutil -m rm -r 'gs://kimstebel-public/'
gsutil mb 'gs://kimstebel-public/'
gsutil -m -h "Cache-Control:public, max-age=86400" cp -z html,css,js -r resources/public/* 'gs://kimstebel-public/'
gsutil -m acl set -r 'public-read' 'gs://kimstebel-public/'
cf push
